/**:
  ros__parameters:
    robot_description_planning:
      # Limits for the Pilz planner
      cartesian_limits:
        max_trans_vel: 1.0
        max_trans_acc: 2.25
        max_trans_dec: 1.0
        max_rot_vel: 1.57
